import { Component } from '@angular/core';
import { IApproved } from 'src/app/model/driverInfo';

@Component({
  selector: 'app-drivers-approved',
  templateUrl: './drivers-approved.component.html',
  styleUrls: ['./drivers-approved.component.scss']
})
export class DriversApprovedComponent {
  drivers_approved: IApproved[] = [
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
    {
      id:1,
      code:'DRV0054',
      name:'Samuel Mcdavid Anyim',
      city: 'Lagos State',
      vehicle_type:'Sedan',
      email:'rex2davy@gmail.com',
      phone:'+2348020974432',
      registered_on:new Date(),
      wallet:5000,
      isEditable: true,
      isNotify: false
    },
  ] 
}
